name: CI
on:
    push:
        branches:
            - main

jobs:
    deploy:
        name: 'Deploy'
        runs-on: 'ubuntu-latest'

        if: "!contains(github.event.head_commit.message,'#no-deploy')"
        steps:
            - uses: actions/checkout@v2

            - run: |
                git config --global user.name 'gh-pages-bot'
                git config --global user.email 'gh-pages-bot@martintopolanek.cz'
            - run: yarn install
            - run: yarn deploy
